export const AUTH_TYPE = {
    ONBOARDING_DONE: 'ONBOARDING_DONE',
    RECEIVED_USER_DATA: 'RECEIVED_USER_DATA',
    UPDATE_USER_DATA:'UPDATE_USER_DATA',
    GET_MY_CART_DATA:"GET_MY_CART_DATA",
    DELETE_FROM_MY_CART:"DELETE_FROM_MY_CART",
    ADD_TO_MY_CART:"ADD_TO_MY_CART",
    SET_TOTAL_PRICE:"SET_TOTAL_PRICE"
}